### ISSUE TITLE
无法拉下3rd 下submodule

### ISSUE THREAD

**Issue by samuelyao314** [zhandouxiaojiji/skynet-creator#1]
fatal: clone of 'git@github.com:zhandouxiaojiji/lua-fog.git' into submodule path '/data/home/user00/skynet-creator/3rd/fog' failed
Failed to clone '3rd/fog'. Retry scheduled
Cloning into '/data/home/user00/skynet-creator/3rd/fsm'...
Cloning into '/data/home/user00/skynet-creator/3rd/git-hooks'...
Permission denied (publickey).

**Comment by zhandouxiaojiji** [comment]
疏忽了，url填错了，已更新
